# docker-compose.yml
version: "3.8"
services:
  apache:
    container_name: apache
    build: ./docker/apache
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - ./logs/apache:/var/log/apache2
      - ./src/backend:/usr/local/apache2/htdocs/backend
  php:
    container_name: php
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./src/backend:/usr/local/apache2/htdocs/backend
    working_dir: /usr/local/apache2/htdocs/backend
  composer:
    container_name: composer
    image: composer/composer
    volumes:
      - ./src/backend:/usr/local/apache2/htdocs/backend
    working_dir: /usr/local/apache2/htdocs/backend
    command: install
  mongo:
    image: mongo:5.0
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./database/mongodb/db:/data/db
      - ./database/mongodb/dev.archive:/Databases/dev.archive
      - ./database/mongodb/production:/Databases/production
    command: [--auth]
    user: "mongodb"  # Set the user for MongoDB

  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"
